apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: mongodb-container
        resources:
          limits:
            memory: "1500Mi"