kind: Secret
apiVersion: v1
metadata:
  name: argocd-vault-plugin-credentials
  namespace: argocd
type: Opaque
data:
  AVP_AUTH_TYPE: YXBwcm9sZQ==  # 'approle' base64 encoded
  AVP_ROLE_ID: YzZkYzRhOWMtMjg2Ny1iZDM0LTY3OTQtNmI4ODMwYzY3MWNk # replace with your base64 encoded role_id
  AVP_SECRET_ID: Mzg0M2E0ZTgtMmM3YS1iYjFjLTMzZmQtNDRkMGIzZjIyOGJi  # '3843a4e8-2c7a-bb1c-33fd-44d0b3f228bb' base64 encoded
  AVP_TYPE: dmF1bHQ=  # 'vault' base64 encoded
  VAULT_ADDR: aHR0cDovL3ZhdWx0LnZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsOjgyMDA=  # 'http://vault.vault.svc.cluster.local:8200' base64 encoded