apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  template:
    spec:
      containers:
      - name: mongodb-container
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_DATABASE
          value: "bezkoder_db"